#!/bin/bash

CONFIG_DIR="$HOME/.config/Kvantum"
CONFIG_FILE="$CONFIG_DIR/kvantum.kvconfig"

while [ "$XDG_CURRENT_DESKTOP" != "KDE" ] && ! pgrep -x "plasmashell" > /dev/null; do
    echo "[DEBUG] Waiting for KDE Plasma session to start..."
    sleep 3
done
sleep 5

apply_theme() {
    echo "[DEBUG] Checking Kvantum Config..."
    if [ -f "$CONFIG_FILE" ]; then
        THEME=$(grep -i '^theme=' "$CONFIG_FILE" | cut -d'=' -f2 | tr -d '[:space:]')
        if [ -n "$THEME" ]; then
            echo "[DEBUG] Found Theme is : $THEME. Applying..."
            plasma-apply-colorscheme "$THEME"
        else
            echo "[DEBUG] 'theme=' Line is empty or isn't found."
        fi
    else
        echo "[DEBUG] $CONFIG_FILE File Not found."
    fi
}

mkdir -p "$CONFIG_DIR"
apply_theme
echo "[DEBUG] Monitoring $CONFIG_DIR..."

inotifywait -e modify,create,moved_to "$CONFIG_DIR" | while read -r path action file; do
    if [ "$file" = "kvantum.kvconfig" ]; then
        sleep 0.5
        apply_theme
    fi
done
